apiVersion: apps/v1
kind: Deployment
metadata:
  name: portifolio-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portifolio-app
  template:
    metadata:
      labels:
        app: portifolio-app
    spec:
      containers:
      - name: portifolio-app
        image: lima2803/portifolio-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: app-config