apiVersion: apps/v1
kind: Deployment
metadata:
  name: portifolio-backend
  namespace: staging
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: portifolio-backend
  template:
    metadata:
      labels:
        app: portifolio-backend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: portifolio-backend
        image: lima2803/portifolio-backend:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: portifolio-backend-service
  namespace: staging
spec:
  selector:
    app: portifolio-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort 
